/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AButtonGroup: typeof import('ant-design-vue/es')['ButtonGroup']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BoxDog: typeof import('./src/components/BoxDog/BoxDog.vue')['default']
    DynamicTitle: typeof import('./src/components/DynamicTitle/DynamicTitle.vue')['default']
    LoginPage: typeof import('./src/views/Login/LoginPage.vue')['default']
    RegisterPage: typeof import('./src/views/Register/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetyOutlined: typeof import('@ant-design/icons-vue')['SafetyOutlined']
    TabletOutlined: typeof import('@ant-design/icons-vue')['TabletOutlined']
    TestI18n: typeof import('./src/views/TestI18n.vue')['default']
    TestTheme: typeof import('./src/views/TestTheme.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
