/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AQrcode: typeof import('ant-design-vue/es')['QRCode']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BoxDog: typeof import('./src/components/BoxDog/BoxDog.vue')['default']
    Card3D: typeof import('./src/components/Card3D/Card3D.vue')['default']
    Clouds: typeof import('./src/components/Clouds/Clouds.vue')['default']
    CommentInput: typeof import('./src/components/CommentReply/src/CommentInput/CommentInput.vue')['default']
    CommentList: typeof import('./src/components/CommentReply/src/CommentList/CommentList.vue')['default']
    CommentReply: typeof import('./src/components/CommentReply/index.vue')['default']
    DynamicTitle: typeof import('./src/components/DynamicTitle/DynamicTitle.vue')['default']
    EffectsCard: typeof import('./src/components/EffectsCard/EffectsCard.vue')['default']
    ForgetPage: typeof import('./src/views/Forget/ForgetPage.vue')['default']
    GithubOutlined: typeof import('@ant-design/icons-vue')['GithubOutlined']
    LandingPage: typeof import('./src/views/Landing/LandingPage.vue')['default']
    LoginFooter: typeof import('./src/views/Login/LoginFooter.vue')['default']
    LoginPage: typeof import('./src/views/Login/LoginPage.vue')['default']
    MainPage: typeof import('./src/views/Main/MainPage.vue')['default']
    NotFound: typeof import('./src/views/404/NotFound.vue')['default']
    QqOutlined: typeof import('@ant-design/icons-vue')['QqOutlined']
    QRLogin: typeof import('./src/views/QRLogin/QRLogin.vue')['default']
    QRLoginFooter: typeof import('./src/views/QRLogin/QRLoginFooter.vue')['default']
    ReplyInput: typeof import('./src/components/CommentReply/src/ReplyInput/ReplyInput.vue')['default']
    ReplyList: typeof import('./src/components/CommentReply/src/ReplyList/ReplyList.vue')['default']
    ReplyReply: typeof import('./src/components/CommentReply/src/ReplyReplyInput/ReplyReply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetyOutlined: typeof import('@ant-design/icons-vue')['SafetyOutlined']
    TabletOutlined: typeof import('@ant-design/icons-vue')['TabletOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WechatOutlined: typeof import('@ant-design/icons-vue')['WechatOutlined']
  }
}
